<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

   require_once(APPPATH.'libraries/domain.php');
   require_once(APPPATH.'libraries/domain_persistence.php');
   require_once(APPPATH.'libraries/domain_presentation.php');
   require_once(APPPATH.'libraries/party.php');
   require_once(APPPATH.'libraries/party_persistence.php');
   require_once(APPPATH.'libraries/party_presentation.php');
   require_once(APPPATH.'libraries/party_role.php');
   require_once(APPPATH.'libraries/party_role_persistence.php');
   require_once(APPPATH.'libraries/party_role_presentation.php');
   require_once(APPPATH.'libraries/person.php');
   require_once(APPPATH.'libraries/person_persistence.php');
   require_once(APPPATH.'libraries/person_presentation.php');
   require_once(APPPATH.'libraries/organization.php');
   require_once(APPPATH.'libraries/organization_persistence.php');
   require_once(APPPATH.'libraries/organization_presentation.php');
// #above are highly depended on
// require_once(APPPATH.'libraries/account_instance.php');
// require_once(APPPATH.'libraries/account_persistence.php');
// require_once(APPPATH.'libraries/account_presentation.php');
// require_once(APPPATH.'libraries/account_amount.php');
// require_once(APPPATH.'libraries/account_amount_persistence.php');
// require_once(APPPATH.'libraries/account_amount_presentation.php');
// require_once(APPPATH.'libraries/account_entry.php');
// require_once(APPPATH.'libraries/account_entry_persistence.php');
// require_once(APPPATH.'libraries/account_entry_presentation.php');
// require_once(APPPATH.'libraries/account_recurring.php');
// require_once(APPPATH.'libraries/account_recurring_persistence.php');
// require_once(APPPATH.'libraries/account_recurring_presentation.php');
 require_once(APPPATH.'libraries/agent_instance.php');
// require_once(APPPATH.'libraries/agent_persistence.php');
// require_once(APPPATH.'libraries/agent_presentation.php');
 require_once(APPPATH.'libraries/charge.php');
// require_once(APPPATH.'libraries/charge_persistence.php');
// require_once(APPPATH.'libraries/charge_presentation.php');
   require_once(APPPATH.'libraries/child_attribute.php');
// require_once(APPPATH.'libraries/child_attribute_persistence.php');
// require_once(APPPATH.'libraries/child_attribute_presentation.php');
 require_once(APPPATH.'libraries/child_instance.php');
// require_once(APPPATH.'libraries/child_persistence.php');
// require_once(APPPATH.'libraries/child_presentation.php');
 require_once(APPPATH.'libraries/court_instance.php');
// require_once(APPPATH.'libraries/court_persistence.php');
// require_once(APPPATH.'libraries/court_presentation.php');
    require_once(APPPATH.'libraries/defendant_instance.php');
// require_once(APPPATH.'libraries/defendant_persistence.php');
// require_once(APPPATH.'libraries/defendant_presentation.php');
    require_once(APPPATH.'libraries/bailbond_instance.php');
// require_once(APPPATH.'libraries/bailbond_persistence.php');
// require_once(APPPATH.'libraries/bailbond_presentation.php');
   require_once(APPPATH.'libraries/document_instance.php');
// require_once(APPPATH.'libraries/document_persistence.php');
// require_once(APPPATH.'libraries/document_presentation.php');
   require_once(APPPATH.'libraries/electronic_address.php');
   require_once(APPPATH.'libraries/electronic_address_persistence.php');
   require_once(APPPATH.'libraries/electronic_address_presentation.php');
   require_once(APPPATH.'libraries/employer.php');
// require_once(APPPATH.'libraries/employer_persistence.php');
// require_once(APPPATH.'libraries/employer_presentation.php');
   require_once(APPPATH.'libraries/employment_attribute.php');
// require_once(APPPATH.'libraries/employment_attribute_persistence.php');
// require_once(APPPATH.'libraries/employment_attribute_presentation.php');
   require_once(APPPATH.'libraries/financial_account_attribute.php');
// require_once(APPPATH.'libraries/financial_account_attribute_persistence.php');
// require_once(APPPATH.'libraries/financial_account_attribute_presentation.php');
    require_once(APPPATH.'libraries/indemnitor.php');
// require_once(APPPATH.'libraries/indemnitor_persistence.php');
// require_once(APPPATH.'libraries/indemnitor_presentation.php');
    require_once(APPPATH.'libraries/indemnitor_attribute.php');
// require_once(APPPATH.'libraries/indemnitor_attribute_persistence.php');
// require_once(APPPATH.'libraries/indemnitor_attribute_presentation.php');
    require_once(APPPATH.'libraries/personal_attribute.php');
// require_once(APPPATH.'libraries/personal_attribute_persistence.php');
// require_once(APPPATH.'libraries/personal_attribute_presentation.php');
 require_once(APPPATH.'libraries/postal_address.php');
 require_once(APPPATH.'libraries/postal_address_attribute.php');
//  require_once(APPPATH.'libraries/postal_address_attribute_persistence.php');
// require_once(APPPATH.'libraries/postal_address_attribute_presentation.php');
 require_once(APPPATH.'libraries/postal_address_persistence.php');
// require_once(APPPATH.'libraries/postal_address_presentation.php');
 require_once(APPPATH.'libraries/power.php');
// require_once(APPPATH.'libraries/PowerInfo.php');
 
 require_once(APPPATH.'libraries/power_persistence.php');
// require_once(APPPATH.'libraries/power_presentation.php');
    require_once(APPPATH.'libraries/reference.php');
// require_once(APPPATH.'libraries/reference_persistence.php');
// require_once(APPPATH.'libraries/reference_presentation.php');
   require_once(APPPATH.'libraries/reference_attribute.php');
// require_once(APPPATH.'libraries/reference_attribute_persistence.php');
// require_once(APPPATH.'libraries/reference_attribute_presentation.php');
// require_once(APPPATH.'libraries/school.php');
// require_once(APPPATH.'libraries/school_persistence.php');
// require_once(APPPATH.'libraries/school_presentation.php');
 require_once(APPPATH.'libraries/spouse.php');
// require_once(APPPATH.'libraries/spouse_persistence.php');
// require_once(APPPATH.'libraries/spouse_presentation.php');
 require_once(APPPATH.'libraries/spouse_attribute.php');
// require_once(APPPATH.'libraries/spouse_attribute_persistence.php');
// require_once(APPPATH.'libraries/spouse_attribute_presentation.php');
   require_once(APPPATH.'libraries/supervisor.php');
// require_once(APPPATH.'libraries/supervisor_persistence.php');
// require_once(APPPATH.'libraries/supervisor_presentation.php');
 require_once(APPPATH.'libraries/surety.php');
// require_once(APPPATH.'libraries/surety_persistence.php');
// require_once(APPPATH.'libraries/surety_presentation.php');
   require_once(APPPATH.'libraries/telecommunication_number.php');
   require_once(APPPATH.'libraries/telecommunication_number_persistence.php');
// require_once(APPPATH.'libraries/telecommunication_number_presentation.php');
   require_once(APPPATH.'libraries/union.php');
// require_once(APPPATH.'libraries/union_persistence.php');
// require_once(APPPATH.'libraries/union_presentation.php');
   require_once(APPPATH.'libraries/user_instance.php');
   require_once(APPPATH.'libraries/user_persistence.php');
   require_once(APPPATH.'libraries/user_presentation.php');
   require_once(APPPATH.'libraries/vehicle_attribute.php');
// require_once(APPPATH.'libraries/vehicle_attribute_persistence.php');
// require_once(APPPATH.'libraries/vehicle_attribute_presentation.php');

#Empty Class so file doesn't throw error when loading other classes
class Domain_Loader{}

/* End of file domain_loader.php */
/* Location: ./application/libraries/domain_loader.php */